# Generated by Django 3.2.25 on 2025-06-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250610_1722'),
        ('blog', '0003_obraarte'),
    ]

    operations = [
    ]
